// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaZh_NtJt_gWYkBBxldptCZgDwusx1Chw',
    appId: '1:841084457590:web:7694a634351ab9eaed0557',
    messagingSenderId: '841084457590',
    projectId: 'go-recipes-2024-56746',
    authDomain: 'go-recipes-2024-56746.firebaseapp.com',
    storageBucket: 'go-recipes-2024-56746.firebasestorage.app',
    measurementId: 'G-PGKSXJLN80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs6_BSxoFb6DoXnA5OaCIigjUeHKMahE4',
    appId: '1:841084457590:android:7943858d2dcc2590ed0557',
    messagingSenderId: '841084457590',
    projectId: 'go-recipes-2024-56746',
    storageBucket: 'go-recipes-2024-56746.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjOp8WsagoGWd7CTAwv3T9pgDGliepBuE',
    appId: '1:841084457590:ios:64c4306583a5554eed0557',
    messagingSenderId: '841084457590',
    projectId: 'go-recipes-2024-56746',
    storageBucket: 'go-recipes-2024-56746.firebasestorage.app',
    iosBundleId: 'com.example.goRecipes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjOp8WsagoGWd7CTAwv3T9pgDGliepBuE',
    appId: '1:841084457590:ios:64c4306583a5554eed0557',
    messagingSenderId: '841084457590',
    projectId: 'go-recipes-2024-56746',
    storageBucket: 'go-recipes-2024-56746.firebasestorage.app',
    iosBundleId: 'com.example.goRecipes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaZh_NtJt_gWYkBBxldptCZgDwusx1Chw',
    appId: '1:841084457590:web:e05b95511363a20bed0557',
    messagingSenderId: '841084457590',
    projectId: 'go-recipes-2024-56746',
    authDomain: 'go-recipes-2024-56746.firebaseapp.com',
    storageBucket: 'go-recipes-2024-56746.firebasestorage.app',
    measurementId: 'G-9JHZCVW4MV',
  );
}
