import 'package:cloud_firestore/cloud_firestore.dart';

class Favorite {
  String? id;       // The unique ID for the favorite record (could be auto-generated by Firestore)
  String? userId;   // The ID of the user who favorited the recipe
  String? recipeId; // The ID of the recipe that has been favorited

  // Constructor
  Favorite({
    this.id,
    this.userId,
    this.recipeId,
  });

  // Named constructor for creating a Favorite from a map (e.g., from Firestore)
  Favorite.fromMap(Map<String, dynamic> map)
      : id = map['id'],
        userId = map['userId'],
        recipeId = map['recipeId'];

  // Method to convert the Favorite instance into a map (e.g., for saving to Firestore)
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'userId': userId,
      'recipeId': recipeId,
    };
  }

  // fromFirestore: A method to create a Favorite object from a Firestore document
  factory Favorite.fromFirestore( 
    DocumentSnapshot<Map<String, dynamic>> doc, SnapshotOptions? options) {
    final data = doc.data()!;
    return Favorite(
      id: data['id'],
      userId: data['userId'],
      recipeId: data['recipeId'],
    );
  }

  // toFirestore: A method to convert a Favorite object to a Firestore document
  Map<String, dynamic> toFirestore() {
    return {
      'id': id,
      'userId': userId,
      'recipeId': recipeId,
    };
  }

  // Optional: A method to validate the data if needed
  bool isValid() {
    return userId != null && recipeId != null;
  }
}
